spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    format:
      date-time: iso